
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Controller.LoginController;
import Model.DAO.Banco;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author wesle
 */
public class Login extends javax.swing.JFrame {

    private final LoginController controller;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        controller = new LoginController(this);
        Banco.inicia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        senha = new javax.swing.JPasswordField();
        usuario = new javax.swing.JTextField();
        Usuário5 = new javax.swing.JLabel();
        Senha4 = new javax.swing.JLabel();
        Login3 = new javax.swing.JLabel();
        Painel2 = new javax.swing.JLabel();
        ImagemFundo1 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 700, 190, 40));

        senha.setBackground(new java.awt.Color(255, 255, 255));
        senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaActionPerformed(evt);
            }
        });
        getContentPane().add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 630, 300, 40));

        usuario.setBackground(new java.awt.Color(255, 255, 255));
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 320, 40));

        Usuário5.setBackground(new java.awt.Color(255, 255, 255));
        Usuário5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Usuário5.setForeground(new java.awt.Color(255, 255, 255));
        Usuário5.setText("Usuário");
        getContentPane().add(Usuário5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        Senha4.setBackground(new java.awt.Color(255, 255, 255));
        Senha4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Senha4.setForeground(new java.awt.Color(255, 255, 255));
        Senha4.setText("Senha");
        getContentPane().add(Senha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, -1, -1));

        Login3.setBackground(new java.awt.Color(255, 255, 255));
        Login3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Login3.setForeground(new java.awt.Color(255, 255, 255));
        Login3.setText("Login");
        getContentPane().add(Login3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        Painel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\wesle\\OneDrive\\Documentos\\NetBeansProjects\\BarberShop\\src\\main\\java\\View\\imagens\\painel-login.png")); // NOI18N
        getContentPane().add(Painel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 560, 580));

        ImagemFundo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\wesle\\OneDrive\\Documentos\\NetBeansProjects\\BarberShop\\src\\main\\java\\View\\imagens\\Logo.jpg")); // NOI18N
        getContentPane().add(ImagemFundo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // executa quando clico no botão
        this.controller.entrarNoSistema();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagemFundo1;
    private javax.swing.JLabel Login3;
    private javax.swing.JLabel Painel2;
    private javax.swing.JLabel Senha4;
    private javax.swing.JLabel Usuário5;
    private javax.swing.JButton jButton1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables

    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }

    public JPasswordField getSenha() {
        return senha;
    }

    public void setSenha(JPasswordField senha) {
        this.senha = senha;
    }

    public JTextField getUsuario() {
        return usuario;
    }

    public void setUsuario(JTextField usuario) {
        this.usuario = usuario;
    }
    
    
}
